import { SpeedInsights } from "@vercel/speed-insights/next"
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html>
      <body className="flex flex-col h-screen justify-start">
        <div>{children}</div>
        <SpeedInsights />
        {/* <footer className="mt-auto">
          <Footer />
        </footer> */}
      </body>
    </html>
  )
}
